version: '3'

services:
  web:
   container_name: web 
   build:
     context: hr-web
   image: hr-web
   ports:
      - 9999:8080   
   expose:
      - 8080
   depends_on:
      - rest
  
  rest:  
   container_name: rest 
   build:
     context: hr-rest
   image: hr-rest
   ports:
      - 8181:8080   
   expose:
      - 8080
   restart: on-failure:3     
   depends_on:
      - db
      - mongo      
   links:
      - db:db  
      - mongo:mongo        

  db:
    image: postgres:9.3
    environment:
      POSTGRES_PASSWORD: example
    restart: always
    ports:
      - 5432:5432   
    expose:
      - 5432    
    command:
      - -c
      - max_prepared_transactions=100
      
  mongo:
    image: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
      
  bonita:
    image: bonita
    ports:
      - 8080:8080
    environment:
      - POSTGRES_ENV_POSTGRES_PASSWORD=example
      - DB_VENDOR=postgres
      - DB_HOST=db
      - TENANT_LOGIN=tech_user
      - TENANT_PASSWORD=secret
      - PLATFORM_LOGIN=pfadmin
      - PLATFORM_PASSWORD=pfsecret
    restart: on-failure:2
    depends_on:
      - db
    entrypoint:
      - bash
      - -c
      - |
        set -e
        echo 'Waiting for Postgres to be available'
        export PGPASSWORD="$$POSTGRES_ENV_POSTGRES_PASSWORD"
        maxTries=10
        while [ "$$maxTries" -gt 0 ] && ! psql -h "$$DB_HOST" -U 'postgres' -c '\l'; do
            let maxTries--
            sleep 1
        done
        echo
        if [ "$$maxTries" -le 0 ]; then
            echo >&2 'error: unable to contact Postgres after 10 tries'
            exit 1
        fi
        exec /opt/files/startup.sh
        
        